services:
  - type: web
    name: django-media-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fifth_contact_session.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: fifth_contact_session.settings
      - key: PYTHON_VERSION
        value: 3.10
